src/Detail.tsx
src/components/Footer.tsx
src/components/LanguageMenu.tsx
src/components/Search/SearchResults.tsx
src/components/Text/TextComponent.tsx
src/components/Text/TextHighlighting.tsx
src/components/Text/TextPanel.tsx
src/components/common/CheckboxGroupComponent.tsx
src/components/common/SelectComponent.tsx
src/projects/default/SearchItem.tsx
src/projects/republic/SearchItem.tsx
src/projects/republic/config/index.tsx

Improvements on digital accessibility.

digital accessibility

---

src/components/Text/Annotated/AnnotatedText.tsx
tailwind.config.default.js
tailwind.config.globalise.js
tailwind.config.hooft.js
tailwind.config.mondriaan.js
tailwind.config.republic.js
tailwind.config.suriano.js
tailwind.config.translatin.js
tailwind.config.vangogh.js

Create default tailwind config to prevent missing annotation variables
Positive side effect: it also removes the duplication in tailwind configs

Fix missing annotation tailwind variables when building project other than republic

---

src/assets/Icon-chairman-hammer.svg

Hammer icon for marking the chairman.

Hammer icon

---

src/components/Search/Search.tsx
src/components/Text/Annotated/utils/createAnnotationClasses.ts
src/projects/republic/annotation/EntitySummary.tsx
src/projects/republic/annotation/ProjectAnnotationModel.ts
src/projects/republic/annotation/toEntitySearchQuery.ts
src/projects/suriano/annotation/EntitySummary.tsx

Depends on PRs https://github.com/knaw-huc/textannoviz/pull/205 and https://github.com/knaw-huc/textannoviz/pull/207

Linking entity to new tav search screen

---

src/components/Search/Search.tsx
src/projects/republic/annotation/ProjectAnnotationModel.ts

Depends on https://github.com/knaw-huc/textannoviz/pull/205 , https://github.com/knaw-huc/textannoviz/pull/207 and https://github.com/knaw-huc/textannoviz/pull/211

Fix facets not showing selected entity in search screen when loading query from url

---

src/components/Search/Search.tsx

This PR fixes duplicate search query sent to broccoli

Prevent duplicate search calls to broccoli

---

src/components/Search/util/createAggs.ts
src/model/ProjectConfig.ts
src/projects/republic/config/index.tsx

Entiteitenfacetten default op A-Z sortering zetten (Republic)

---

src/projects/republic/config/dutchRepublicLabels.ts

Fixes https://github.com/knaw-huc/textannoviz/issues/273

Add 'resultaat' to republic prev and next search result labels

---

src/components/Search/histogram/BarChartHistogram.tsx
src/model/Labels.ts
src/projects/default/config/dutchLabels.ts
src/projects/default/config/englishLabels.ts
src/projects/republic/config/dutchRepublicLabels.ts

Fixes https://github.com/knaw-huc/textannoviz/issues/271

Add occurrences per year label, with republic version

---

src/components/Search/SearchPagination.tsx

Fixes https://github.com/knaw-huc/textannoviz/issues/289
Also disable prev and next result page buttons when there is no prev or next page.

Fix browsing to next page when there is no next page 

---

src/components/common/icons/HammerIcon.tsx
src/model/AnnoRepoAnnotation.ts
src/projects/republic/MetadataPanel.tsx
src/projects/republic/config/dutchRepublicLabels.ts
src/projects/republic/config/englishRepublicLabels.ts

Revolves #257, #167, #171, #172.

New delegates data metadata panel

---

src/projects/republic/config/dutchRepublicLabels.ts

Changed label delegate facet from "Aanwezige gedeputeerde" to "Gedeputeerde"

---

src/projects/republic/config/index.tsx

Change logoHref to goetgevonden.nl

---

src/components/common/icons/ArchiveIcon.tsx
src/model/AnnoRepoAnnotation.ts
src/projects/republic/MetadataPanel.tsx
src/projects/republic/annotation/EntitySummary.tsx
src/projects/republic/annotation/ProjectAnnotationModel.ts
src/projects/republic/annotation/ProvenanceButton.tsx
src/projects/republic/config/dutchRepublicLabels.ts

Work in progress, waiting for provenance urls in annotations
Resolves https://github.com/knaw-huc/textannoviz/issues/224

Provenance links

---

src/components/Text/Annotated/ScrollableModal.tsx

Resolves https://github.com/knaw-huc/textannoviz/issues/302

Allow closing a modal by clicking outside the modal

---

src/components/Text/Annotated/utils/createLineOffsets.spec.ts
src/projects/republic/config/dutchRepublicLabels.ts
src/projects/republic/config/index.tsx

Resolves https://github.com/knaw-huc/textannoviz/issues/294
Resolves https://github.com/knaw-huc/textannoviz/issues/296
Resolves https://github.com/knaw-huc/textannoviz/issues/298

Republic tweaks 296 294 298

---

src/projects/republic/config/dutchRepublicLabels.ts

Resolves https://github.com/knaw-huc/textannoviz/issues/297

Translate updated facet keys to dutch republic labels

---

src/model/AnnoRepoAnnotation.ts
src/projects/republic/MetadataPanel.tsx
src/projects/republic/config/index.tsx

It can be merged when the ES index is 100% full, and data has been tested in TAV.

Use ES index republic-2024.11.30

---

src/stores/search/toRequestBody.ts

See [f7d8c9f4](https://github.com/knaw-huc/textannoviz/commit/f7d8c9f497fc467da18aa7f45dc28799d99262f6#diff-1014945fac6a650b125b216fb80d8ae2cf00561a58b05ad885baa81dcf121cd6L80) (search-query-slice.ts) for context

Revert additional debug checks when creating request body

---

src/components/Detail/useDetailNavigation.tsx
src/components/Footer/DetailSearchResultsNavigation.tsx

Resolves https://github.com/knaw-huc/textannoviz/issues/336

Fix error screen when entering detail page without search query

---

src/components/Detail/useDetailNavigation.tsx
src/projects/default/SearchItem.tsx
src/projects/globalise/SearchItem.tsx
src/projects/mondriaan/SearchItem.tsx
src/projects/republic/SearchItem.tsx
src/projects/suriano/SearchItem.tsx
src/projects/translatin/SearchItem.tsx
src/projects/vangogh/SearchItem.tsx

Depends on https://github.com/knaw-huc/textannoviz/pull/345

Use query.fullText instead of dedicated highlight url param

---

src/utils/UrlParamUtils.ts

Fixes https://github.com/knaw-huc/textannoviz/issues/374

Do not push to browser history when next url is equal to prev url

---

src/components/Search/KeywordFacet.tsx

Now facets are grouped by being selected or not: only entries that are not selected will be sliced.
Can be tested in the republic project with this url:
http://localhost:5173/?query[terms][locationName][]=Frankrijk&query[terms][locationId][]=L0007323

Fix selected entities not showing up after slicing
